name: cat_printer_flutter_example
description: Example app demonstrating how to use cat_printer_flutter library.
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # The cat_printer_flutter library
  cat_printer_flutter:
    path: ../
  
  # UI dependencies
  cupertino_icons: ^1.0.8
  
  # Image processing dependencies
  file_picker: ^6.2.1
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true